# Data Quality Report

In [30]:
# importing libraries
import pandas as pd
import sqlite3

### Loading data

In [39]:
# csv files
patient_journey = pd.read_csv('../data/patient_journey.csv')
provider_master = pd.read_csv('../data/provider_master.csv')
communication_logs = pd.read_csv('../data/communication_logs.csv')
treatment_outcome = pd.read_csv('../data/treatment_outcomes.csv')
country_reference = pd.read_csv('../data/country_reference.csv')

# sql fFile
conn = sqlite3.connect('../data/mte_patient_intelligence.db')

### Patient Journey

In [8]:
patient_journey.columns.to_list()

['patient_id',
 'inquiry_date',
 'country',
 'age_group',
 'gender',
 'treatment_category',
 'provider_id',
 'lead_source',
 'coordinator_id',
 'budget_band',
 'medical_urgency',
 'intent_score',
 'response_time_hours',
 'engagement_score',
 'consultation_booked',
 'quote_shared',
 'treatment_completed',
 'follow_up_completed',
 'current_stage',
 'drop_off_flag',
 'drop_off_stage',
 'reason_for_drop_off',
 'estimated_case_value_inr',
 'actual_revenue_inr',
 'service_cost_inr',
 'satisfaction_score']

In [5]:
patient_journey.head()

,patient_id,inquiry_date,country,age_group,gender,treatment_category,provider_id,lead_source,coordinator_id,budget_band,...,treatment_completed,follow_up_completed,current_stage,drop_off_flag,drop_off_stage,reason_for_drop_off,estimated_case_value_inr,actual_revenue_inr,service_cost_inr,satisfaction_score
0,MTE-PAT-00001,2025-11-12 18:00:00,Thailand,40-49,Other/Not shared,Oncology,PVD-022,Phone,COORD-08,Low,...,0,0,First Response,0,NaN,NaN,780855,0,0,NaN
1,MTE-PAT-00002,2025-04-12 04:00:00,Kenya,60+,Female,Fertility,PVD-022,WhatsApp,COORD-13,High,...,1,1,Follow-up,0,NaN,NaN,270529,270529,161988,7.7
2,MTE-PAT-00003,2025-12-28 06:00:00,Tanzania,50-59,Male,Oncology,PVD-008,Web Form,COORD-01,High,...,1,0,Treatment Completed,0,NaN,NaN,549181,549181,312857,7.4
3,MTE-PAT-00004,2025-08-31 21:00:00,Oman,40-49,Other/Not shared,Oncology,PVD-005,Phone,COORD-15,High,...,0,0,Consultation,1,Inquiry,Response delay,505922,0,0,NaN
4,MTE-PAT-00005,2025-08-26 18:00:00,Nepal,50-59,Male,Fertility,PVD-009,Phone,COORD-09,Low,...,0,0,First Response,0,NaN,NaN,631722,0,0,NaN

In [11]:
patient_journey.shape

(1500, 26)

In [10]:
patient_journey.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 26 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   patient_id                1500 non-null   str
 1   inquiry_date              1500 non-null   str
 2   country                   1500 non-null   str
 3   age_group                 1500 non-null   str
 4   gender                    1500 non-null   str
 5   treatment_category        1500 non-null   str
 6   provider_id               1500 non-null   str
 7   lead_source               1500 non-null   str
 8   coordinator_id            1500 non-null   str
 9   budget_band               1500 non-null   str
 10  medical_urgency           1500 non-null   str
 11  intent_score              1500 non-null   float64
 12  response_time_hours       1500 non-null   float64
 13  engagement_score          1500 non-null   float64
 14  consultation_booked       1500 non-null   int64
 15  quote_shared              1500 non-null   int64
 16  treatment_completed       1500 non-null   int64
 17  follow_up_completed       1500 non-null   int64
 18  current_stage             1500 non-null   str
 19  drop_off_flag             1500 non-null   int64
 20  drop_off_stage            350 non-null    str
 21  reason_for_drop_off       350 non-null    str
 22  estimated_case_value_inr  1500 non-null   int64
 23  actual_revenue_inr        1500 non-null   int64
 24  service_cost_inr          1500 non-null   int64
 25  satisfaction_score        554 non-null    float64
dtypes: float64(4), int64(8), str(14)
memory usage: 304.8 KB

### Provider Master

In [12]:
provider_master.columns.to_list()

['provider_id',
 'provider_name',
 'region',
 'country',
 'specialty_area',
 'bed_capacity',
 'international_patient_desk',
 'avg_first_response_hours',
 'historical_consultation_conversion_rate',
 'historical_treatment_conversion_rate',
 'follow_up_completion_rate',
 'satisfaction_index',
 'pricing_tier',
 'contract_status']

In [13]:
provider_master.shape

(30, 14)

In [14]:
provider_master.sample(5)

,provider_id,provider_name,region,country,specialty_area,bed_capacity,international_patient_desk,avg_first_response_hours,historical_consultation_conversion_rate,historical_treatment_conversion_rate,follow_up_completion_rate,satisfaction_index,pricing_tier,contract_status
11,PVD-012,MTE Partner Hospital 12,Southeast Asia,Sri Lanka,Fertility,500,Yes,12.9,0.637,0.127,0.505,86.3,Economy,Active
7,PVD-008,MTE Partner Hospital 08,West Africa,Thailand,Transplant Evaluation,250,Yes,9.1,0.525,0.231,0.466,82.6,Premium,Pilot
16,PVD-017,MTE Partner Hospital 17,Southeast Asia,Tanzania,Transplant Evaluation,120,Yes,13.3,0.562,0.281,0.454,87.4,Premium,Active
18,PVD-019,MTE Partner Hospital 19,East Africa,Nepal,Transplant Evaluation,500,Yes,13.0,0.830,0.340,0.808,96.0,Economy,Active
26,PVD-027,MTE Partner Hospital 27,Southeast Asia,Thailand,Oncology,150,Yes,11.9,0.344,0.070,0.497,89.6,Economy,Active

In [15]:
provider_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 14 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   provider_id                              30 non-null     str
 1   provider_name                            30 non-null     str
 2   region                                   30 non-null     str
 3   country                                  30 non-null     str
 4   specialty_area                           30 non-null     str
 5   bed_capacity                             30 non-null     int64
 6   international_patient_desk               30 non-null     str
 7   avg_first_response_hours                 30 non-null     float64
 8   historical_consultation_conversion_rate  30 non-null     float64
 9   historical_treatment_conversion_rate     30 non-null     float64
 10  follow_up_completion_rate                30 non-null     float64
 11  satisfaction_index                       30 non-null     float64
 12  pricing_tier                             30 non-null     str
 13  contract_status                          30 non-null     str
dtypes: float64(5), int64(1), str(8)
memory usage: 3.4 KB

### Communication Logs

In [16]:
communication_logs.columns.to_list()

['communication_id',
 'patient_id',
 'provider_id',
 'timestamp',
 'channel',
 'interaction_type',
 'sent_by',
 'response_sent',
 'response_delay_hours',
 'follow_up_status']

In [17]:
communication_logs.shape

(6025, 10)

In [18]:
communication_logs.sample(5)

,communication_id,patient_id,provider_id,timestamp,channel,interaction_type,sent_by,response_sent,response_delay_hours,follow_up_status
4838,COMM-004839,MTE-PAT-01207,PVD-006,2025-10-24 05:53:27,Web Form,Initial response,Patient,1,13.0,Not required
4607,COMM-004608,MTE-PAT-01149,PVD-009,2025-12-22 01:41:23,Phone,Escalation,Provider Desk,0,NaN,Not required
5776,COMM-005777,MTE-PAT-01433,PVD-012,2025-07-04 05:03:57,Web Form,Post-treatment follow-up,Patient,1,13.4,Completed
3803,COMM-003804,MTE-PAT-00952,PVD-014,2025-01-14 15:01:35,Web Form,Initial response,MedTourEasy Coordinator,0,NaN,Pending
3392,COMM-003393,MTE-PAT-00849,PVD-024,2025-09-16 06:15:53,Web Form,Document request,Automated Workflow,1,15.6,Completed

In [19]:
communication_logs.info()

<class 'pandas.DataFrame'>
RangeIndex: 6025 entries, 0 to 6024
Data columns (total 10 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   communication_id      6025 non-null   str
 1   patient_id            6025 non-null   str
 2   provider_id           6025 non-null   str
 3   timestamp             6025 non-null   str
 4   channel               6025 non-null   str
 5   interaction_type      6025 non-null   str
 6   sent_by               6025 non-null   str
 7   response_sent         6025 non-null   int64
 8   response_delay_hours  4612 non-null   float64
 9   follow_up_status      6025 non-null   str
dtypes: float64(1), int64(1), str(8)
memory usage: 470.8 KB

### Treatment Outcome

In [20]:
treatment_outcome.columns.to_list()

['patient_id',
 'provider_id',
 'treatment_category',
 'treatment_date',
 'length_of_stay_days',
 'actual_revenue_inr',
 'service_cost_inr',
 'gross_margin_inr',
 'readmission_within_30d',
 'follow_up_rating']

In [21]:
treatment_outcome.shape

(554, 10)

In [22]:
treatment_outcome.sample(5)

,patient_id,provider_id,treatment_category,treatment_date,length_of_stay_days,actual_revenue_inr,service_cost_inr,gross_margin_inr,readmission_within_30d,follow_up_rating
436,MTE-PAT-01186,PVD-009,Fertility,2025-04-22,9,273825,131817,142008,0,8.8
453,MTE-PAT-01238,PVD-015,Oncology,2025-05-24,18,588338,300703,287635,0,6.4
324,MTE-PAT-00896,PVD-017,Neurology,2025-04-24,6,467840,234876,232964,0,7.6
201,MTE-PAT-00540,PVD-013,Bariatric Surgery,2026-02-07,21,459513,211551,247962,1,7.5
384,MTE-PAT-01044,PVD-011,Dental,2025-10-08,4,92563,62533,30030,0,6.5

In [23]:
treatment_outcome.info()

<class 'pandas.DataFrame'>
RangeIndex: 554 entries, 0 to 553
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   patient_id              554 non-null    str
 1   provider_id             554 non-null    str
 2   treatment_category      554 non-null    str
 3   treatment_date          554 non-null    str
 4   length_of_stay_days     554 non-null    int64
 5   actual_revenue_inr      554 non-null    int64
 6   service_cost_inr        554 non-null    int64
 7   gross_margin_inr        554 non-null    int64
 8   readmission_within_30d  554 non-null    int64
 9   follow_up_rating        554 non-null    float64
dtypes: float64(1), int64(5), str(4)
memory usage: 43.4 KB

### Country Reference

In [24]:
country_reference.columns.to_list()

['country',
 'region',
 'avg_travel_lead_time_days',
 'requires_medical_visa',
 'currency',
 'baseline_response_expectation_hours',
 'market_priority_score']

In [25]:
country_reference.shape

(12, 7)

In [26]:
country_reference.sample(5)

,country,region,avg_travel_lead_time_days,requires_medical_visa,currency,baseline_response_expectation_hours,market_priority_score
4,Kenya,East Africa,14,No,KES,12,89
8,Sri Lanka,South Asia,37,Yes,THB,6,78
9,Malaysia,West Africa,14,Case-dependent,KES,8,62
6,Tanzania,East Africa,12,Yes,MYR,8,75
7,Nepal,West Africa,42,Yes,MYR,6,71

In [28]:
country_reference.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   country                              12 non-null     str
 1   region                               12 non-null     str
 2   avg_travel_lead_time_days            12 non-null     int64
 3   requires_medical_visa                12 non-null     str
 4   currency                             12 non-null     str
 5   baseline_response_expectation_hours  12 non-null     int64
 6   market_priority_score                12 non-null     int64
dtypes: int64(3), str(4)
memory usage: 804.0 bytes

### Data Base

In [40]:
tables = pd.read_sql("""
    SELECT name FROM sqlite_schema WHERE type='table';
""", conn)
tables

                 name
0     patient_journey
1     provider_master
2  communication_logs
3  treatment_outcomes
4   country_reference